---
title: "pbmc_pipeline"
author: "Tae Kim"
date: "6/10/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      comment=NA,
                      warning = FALSE,
                      message = FALSE)
library(MultiAssayExperiment)
library(ggplot2)
library(irlba)
library(matrixStats)
library(inline)
library(quadprog)
library(dplyr)
library(reshape)
library(caret)
library(fossil)
library(pracma)
library(scatterplot3d)
library(igraph) #for nmi
library(Rtsne)
library(diceR)
library(gplots)
library(Matrix)
library(plotly)

set.seed(1)
R.utils::sourceDirectory("../../R/", modifiedOnly=FALSE)
Rcpp::sourceCpp('../../src/SCNoisyClustering.cpp')

  heat = function(S){
    ggplot(melt(S), aes(x=X1, y=X2, fill=value)) + geom_tile() + scale_fill_gradient()
  }
```


```{r}
#10X Gemcode - pbmc 3k
orig = readMM('../../data/pbmc3k/matrix.mtx')
genenames = read.table('../../data/pbmc3k/genes.tsv')

#take log
lorig = log(orig + 1)
rm(orig)

#first pc
lorig_pc1 = irlba(lorig, 1)$v[,1]

#zero counts
lorig = as.matrix(lorig)
zeros = colSums(lorig==0)

#check dependency
plot(lorig_pc1 ~ zeros, xlab='zero counts', ylab='pc1')
```

```{r}
#center the lorig
lorig2 = scale(lorig, scale=F)
lorig_pc2 = irlba(lorig2, 1)$v[,1]
plot(lorig_pc2 ~ zeros, xlab='zero counts', ylab='pc1')

#regress out and get residuals
x = zeros - mean(zeros)
lorig_rs = t(t(scale(lorig)) - x %*% (t(x) %*% t(scale(lorig))/(sum(x^2)))); 

#new pc1
lrs_pc1 = irlba(lorig_rs, 1)$v[,1]

#check that the dependency has been removed
plot(lrs_pc1 ~ zeros, xlab='detection rate',
     ylab = 'pc1',
     main='log count matrix after removing pc1')
```

```{r}
#split data for "parallel" computing
splits = ceil(ncol(lorig)/300)
indlist = split(1:2700, sample(rep(1:9, 300)))
X = list()
for (i in 1:9){
  X[[i]] = lorig_rs[,indlist[[i]]]
}

#load reference data
load('../../data/sysdata.rda')
primary_cell_atlas = sysdata$GlobalPanel[[1]]
gene_atlas = sysdata$GlobalPanel[[2]]
rm(sysdata)

#initialize to save results
groupslist = combn(1:9, 2)
N = ncol(groupslist)
cluster_result_geneatlas = matrix(NA, 2700, N)
cluster_result_cellatlas = matrix(NA, 2700, N)

#run the algorithm for each pairs
for (i in 1:N){
  groups = groupslist[,i]
  x = cbind(X[[groups[1]]], X[[groups[2]]])
  rownames(x) = genenames$V2
  int1 = base::intersect(rownames(primary_cell_atlas), rownames(x)) #3680
  int2 = base::intersect(rownames(gene_atlas), rownames(x)) #4004

  ind1 = match(int1, rownames(x))
  x1 = x[ind1, ]
  ind11 = match(int1, rownames(primary_cell_atlas))
  primary_cell_atlas = primary_cell_atlas[ind11, ]

  ind2 = match(int2, rownames(x))
  x2 = x[ind2, ]
  ind22 = match(int2, rownames(gene_atlas))
  gene_atlas = gene_atlas[ind22, ]

  projection1 = t(t(x1) %*% as.matrix(primary_cell_atlas))/nrow(x1)
  colnames(projection1) = factor(colnames(projection1), levels = colnames(projection1))
  projection1 = scale(projection1^4)
  res = SLSL(projection1, filter = T, kernel_type = "euclidean", correct_detection_rate = F)
  cluster_result_geneatlas[c(indlist[[groups[1]]], indlist[[groups[2]]]),i] = res$result


  projection2 = t(t(x2) %*% as.matrix(gene_atlas))/nrow(x2)
  colnames(projection2) = factor(colnames(projection2), levels = colnames(projection2))
  projection2 = scale(projection2^4)
  res = SLSL(projection2, log=T)
  cluster_result_cellatlas[c(indlist[[groups[1]]], indlist[[groups[2]]]),i] = res$result

  gc()
}

rm(X); gc();

final = array(0, dim=c(nrow(cluster_result_cellatlas), ncol(cluster_result_cellatlas),1,1))
final[,,1,1]= cluster_result_cellatlas
k=length(table(as.numeric(cluster_result_cellatlas)))
dimnames(final)[[1]] = paste0('R',1:nrow(cluster_result_cellatlas))
dimnames(final)[[2]] = paste0('C',1:ncol(cluster_result_cellatlas))
dimnames(final)[[3]] = paste0("k")
dimnames(final)[[4]] = as.character(k)
final_cell = CSPA(final, k)

final = array(0, dim=c(nrow(cluster_result_geneatlas), ncol(cluster_result_geneatlas),1,1))
final[,,1,1]= cluster_result_geneatlas
k=length(table(as.numeric(cluster_result_geneatlas)))
dimnames(final)[[1]] = paste0('R',1:nrow(cluster_result_geneatlas))
dimnames(final)[[2]] = paste0('C',1:ncol(cluster_result_geneatlas))
dimnames(final)[[3]] = paste0("k")
dimnames(final)[[4]] = as.character(k)
final_gene = CSPA(final, k)


```

```{r}
library(Rtsne)
x = lorig_rs; rm(lorig_rs); x = x[, unlist(indlist)]
rownames(x) = genenames$V2
int1 = base::intersect(rownames(primary_cell_atlas), rownames(x)) #3680
int2 = base::intersect(rownames(gene_atlas), rownames(x)) #4004

ind1 = match(int1, rownames(x))
x1 = x[ind1, ]
ind11 = match(int1, rownames(primary_cell_atlas))
primary_cell_atlas = primary_cell_atlas[ind11, ]

ind2 = match(int2, rownames(x))
x2 = x[ind2, ]
ind22 = match(int2, rownames(gene_atlas))
gene_atlas = gene_atlas[ind22, ]

projection1 = t(t(x1) %*% as.matrix(primary_cell_atlas))/nrow(x1)
colnames(projection1) = factor(colnames(projection1), levels = colnames(projection1))
projection1 = scale(projection1^4)

projection2 = t(t(x2) %*% as.matrix(gene_atlas))/nrow(x2)
colnames(projection2) = factor(colnames(projection2), levels = colnames(projection2))
projection2 = scale(projection2^4)

cell_tsne = Rtsne(t(projection1), dims=3, perplexity=20, verbose=F, max_iter=1500)
gene_tsne = Rtsne(t(projection2), dims=3, perplexity=20, verbose=F, max_iter=1500)
plot_ly(x=cell_tsne$Y[,1], y=cell_tsne$Y[,2], z=cell_tsne$Y[,3], color = final_cell)
plot_ly(x=gene_tsne$Y[,1], y=gene_tsne$Y[,2], z=gene_tsne$Y[,3], color = final_gene)

```
