// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// sparse_sum
arma::sp_mat sparse_sum(Rcpp::List P, int length);
RcppExport SEXP _SCNoisyClustering_sparse_sum(SEXP PSEXP, SEXP lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type P(PSEXP);
    Rcpp::traits::input_parameter< int >::type length(lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(sparse_sum(P, length));
    return rcpp_result_gen;
END_RCPP
}
// QminusPslice
arma::vec QminusPslice(arma::sp_mat Q, Rcpp::List P, int length);
RcppExport SEXP _SCNoisyClustering_QminusPslice(SEXP QSEXP, SEXP PSEXP, SEXP lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type P(PSEXP);
    Rcpp::traits::input_parameter< int >::type length(lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(QminusPslice(Q, P, length));
    return rcpp_result_gen;
END_RCPP
}
// proj_c
arma::mat proj_c(arma::mat X, arma::mat ref);
RcppExport SEXP _SCNoisyClustering_proj_c(SEXP XSEXP, SEXP refSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ref(refSEXP);
    rcpp_result_gen = Rcpp::wrap(proj_c(X, ref));
    return rcpp_result_gen;
END_RCPP
}
// armapmax
arma::mat armapmax(arma::mat A, double bound);
RcppExport SEXP _SCNoisyClustering_armapmax(SEXP ASEXP, SEXP boundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type bound(boundSEXP);
    rcpp_result_gen = Rcpp::wrap(armapmax(A, bound));
    return rcpp_result_gen;
END_RCPP
}
// armapmin
arma::mat armapmin(arma::mat A, double bound);
RcppExport SEXP _SCNoisyClustering_armapmin(SEXP ASEXP, SEXP boundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type bound(boundSEXP);
    rcpp_result_gen = Rcpp::wrap(armapmin(A, bound));
    return rcpp_result_gen;
END_RCPP
}
// nonnegASC_c
arma::mat nonnegASC_c(arma::mat B);
RcppExport SEXP _SCNoisyClustering_nonnegASC_c(SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(nonnegASC_c(B));
    return rcpp_result_gen;
END_RCPP
}
// get_kernel_matrix
arma::sp_mat get_kernel_matrix(arma::mat X, arma::mat Diff, int k, double sigma);
RcppExport SEXP _SCNoisyClustering_get_kernel_matrix(SEXP XSEXP, SEXP DiffSEXP, SEXP kSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Diff(DiffSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(get_kernel_matrix(X, Diff, k, sigma));
    return rcpp_result_gen;
END_RCPP
}
// sparse_scaledlasso_list_c
Rcpp::List sparse_scaledlasso_list_c(Rcpp::List P, int n, const double tau, const double gamma, double mu, const double rho, const int max_iter, const double eps, const bool verbose);
RcppExport SEXP _SCNoisyClustering_sparse_scaledlasso_list_c(SEXP PSEXP, SEXP nSEXP, SEXP tauSEXP, SEXP gammaSEXP, SEXP muSEXP, SEXP rhoSEXP, SEXP max_iterSEXP, SEXP epsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type P(PSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(sparse_scaledlasso_list_c(P, n, tau, gamma, mu, rho, max_iter, eps, verbose));
    return rcpp_result_gen;
END_RCPP
}
// tsne_c
arma::mat tsne_c(arma::mat X, arma::mat initial_config, int k, int max_iter, double min_cost, int epoch);
RcppExport SEXP _SCNoisyClustering_tsne_c(SEXP XSEXP, SEXP initial_configSEXP, SEXP kSEXP, SEXP max_iterSEXP, SEXP min_costSEXP, SEXP epochSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type initial_config(initial_configSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type min_cost(min_costSEXP);
    Rcpp::traits::input_parameter< int >::type epoch(epochSEXP);
    rcpp_result_gen = Rcpp::wrap(tsne_c(X, initial_config, k, max_iter, min_cost, epoch));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SCNoisyClustering_sparse_sum", (DL_FUNC) &_SCNoisyClustering_sparse_sum, 2},
    {"_SCNoisyClustering_QminusPslice", (DL_FUNC) &_SCNoisyClustering_QminusPslice, 3},
    {"_SCNoisyClustering_proj_c", (DL_FUNC) &_SCNoisyClustering_proj_c, 2},
    {"_SCNoisyClustering_armapmax", (DL_FUNC) &_SCNoisyClustering_armapmax, 2},
    {"_SCNoisyClustering_armapmin", (DL_FUNC) &_SCNoisyClustering_armapmin, 2},
    {"_SCNoisyClustering_nonnegASC_c", (DL_FUNC) &_SCNoisyClustering_nonnegASC_c, 1},
    {"_SCNoisyClustering_get_kernel_matrix", (DL_FUNC) &_SCNoisyClustering_get_kernel_matrix, 4},
    {"_SCNoisyClustering_sparse_scaledlasso_list_c", (DL_FUNC) &_SCNoisyClustering_sparse_scaledlasso_list_c, 9},
    {"_SCNoisyClustering_tsne_c", (DL_FUNC) &_SCNoisyClustering_tsne_c, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_SCNoisyClustering(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
