---
title: "Effects of Correction of Detection Rate"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    theme: yeti
    highlight: tango
    toc: false
    toc_float: 
      collapsed: true
      smooth_scroll: true
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "../analysis")
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      comment = NA)
library(SCNoisyClustering)
library(matrixStats)
library(inline)
library(quadprog)
library(irlba)
library(ggplot2)
library(dplyr)
library(reshape)
library(fossil) #ARI
#library(pracma)
library(Rtsne)
library(diceR)
library(broom)
library(abind)

library(stargazer)

set.seed(1)
# R.utils::sourceDirectory("../../R/", modifiedOnly=FALSE)
# Rcpp::sourceCpp('../../src/SCNoisyClustering.cpp')

heat = function(S){
  ggplot(melt(S), aes(x=X1, y=X2, fill=value)) + geom_tile() + scale_fill_gradient()
}
```

```{r initialize, include=F}
cellcount   = rep(0,8)
genecount   = rep(0,8)
detection   = rep(0,8)
ARI         = data.frame("BEFORE" = rep(0,8), "AFTER" = rep(0,8))
data_list     = c('Kolod','Pollen','Usoskin','Buettner',
                  'Yan','Treutlein','Chu1','Chu2')
correction    = c("BEFORE", "AFTER")

```

```{r Kolod, include = FALSE}
i = 1
load('../data/unnecessary_in_building/1_Kolod.RData')
X        = exp(Test_2_Kolod$in_X)-1;
truth    = Test_2_Kolod$true_labs$V1
numClust = Test_2_Kolod$n_clust;
rm(Test_2_Kolod)

cellcount[i] = ncol(X)
genecount[i] = nrow(X)


logX = log(X+1)

det = colSums(X!=0) / nrow(X)

det2 = qr(det)
R = t(qr.resid(det2, t(logX)))

pca1 = irlba(R,2); pca2 = irlba(logX,2)
dat = data.frame(pc1=c(pca1$v[,1], pca2$v[,1]), detection.rate=rep(det, 2), label=rep(c("After correction", "Before correction"), each=nrow(pca1$v)), truth=as.factor(rep(truth,2)))
ggplot(dat, aes(x=pc1, y=detection.rate, col=truth)) + facet_grid(~label) + geom_point() + ggtitle("PCA")

tsne1 = Rtsne(t(R))
tsne2 = Rtsne(t(logX))

dat = data.frame(v1 = c(tsne1$Y[,1], tsne2$Y[,1]), v2 = c(tsne1$Y[,2], tsne2$Y[,2]), label=rep(c("After correction", "Before correction"), each=nrow(tsne1$Y)), truth = as.factor(rep(truth, 2)))
ggplot(dat, aes(x=v1, y=v2, col=truth)) + facet_grid(~label) + geom_point() + ggtitle("tSNE")

set.seed(1)
res1 = SLSL(X, log=T, filter=F, correct_detection_rate = T, numClust = numClust)
adj.rand.index(res1$result, truth)

set.seed(1)
res2 = SLSL(X, log=T, filter=F, correct_detection_rate = F, numClust = numClust)
adj.rand.index(res2$result, truth)
```




##Pollen

```{r Pollen}
i = 2

load('../data/unnecessary_in_building/2_Pollen.RData')
X        = as.matrix(Pollen$x)
truth    = as.numeric(as.factor(Pollen$label))
numClust = length(unique(truth))
rm(Pollen)

logX = log(X+1)

det = colSums(X!=0) / nrow(X)

det2 = qr(cbind(rep(1,length(det)), det))
R = t(qr.resid(det2, t(logX)))

pca1 = irlba(R,2); pca2 = irlba(logX,2)
dat = data.frame(pc1=c(pca1$v[,1], pca2$v[,1]), detection.rate=rep(det, 2), label=rep(c("After correction", "Before correction"), each=nrow(pca1$v)), true.label=as.factor(rep(truth,2)))
ggplot(dat, aes(x=pc1, y=detection.rate, col=true.label)) + facet_grid(~label) + geom_point() + ggtitle("PCA")

tsne1 = Rtsne(t(R))
tsne2 = Rtsne(t(logX))

dat = data.frame(v1 = c(tsne1$Y[,1], tsne2$Y[,1]), v2 = c(tsne1$Y[,2], tsne2$Y[,2]), label=rep(c("After correction", "Before correction"), each=nrow(tsne1$Y)), true.label = as.factor(rep(truth, 2)))
ggplot(dat, aes(x=v1, y=v2, col=true.label)) + facet_grid(~label) + geom_point() + ggtitle("tSNE")

set.seed(1)
res1 = SLSL(X, log=T, filter=F, correct_detection_rate = T, numClust = numClust)
adj.rand.index(res1$result, truth)

set.seed(1)
res2 = SLSL(X, log=T, filter=F, correct_detection_rate = F, numClust = numClust)
adj.rand.index(res2$result, truth)
```

##Usoskin 
```{r Usoskin, cache=T}
i = 3

load('../data/unnecessary_in_building/3_Usoskin.RData')
X        = as.matrix(Usoskin$X)
truth    = as.numeric(as.factor(as.character(Usoskin$lab1)))
numClust = 4
rm(Usoskin)

logX = log(X+1)

det = colSums(X!=0) / nrow(X)

plot(irlba(logX,1)$v[,1]~log(det))

det2 = qr(cbind(rep(1, length(det)), log(det)))
R = t(qr.resid(det2, t(logX)))

pca1 = irlba(R,2); pca2 = irlba(logX,2)
dat = data.frame(pc1=c(pca1$v[,1], pca2$v[,1]), detection.rate=rep(det, 2), label=rep(c("After correction", "Before correction"), each=nrow(pca1$v)), true.label=as.factor(rep(truth,2)))
ggplot(dat, aes(x=pc1, y=detection.rate, col=true.label)) + facet_grid(~label) + geom_point() + ggtitle("PCA")

tsne1 = Rtsne(t(R), perplexity=20)
tsne2 = Rtsne(t(logX))

dat = data.frame(v1 = c(tsne1$Y[,1], tsne2$Y[,1]), v2 = c(tsne1$Y[,2], tsne2$Y[,2]), label=rep(c("After correction", "Before correction"), each=nrow(tsne1$Y)), true.label = as.factor(rep(truth, 2)))
ggplot(dat, aes(x=v1, y=v2, col=true.label)) + facet_grid(~label) + geom_point() + ggtitle("tSNE")

set.seed(1)
res1 = SLSL(X, log=T, filter=F, correct_detection_rate = T, numClust = numClust)
adj.rand.index(res1$result, truth)

set.seed(1)
res2 = SLSL(X, log=T, filter=F, correct_detection_rate = F, numClust = numClust)
adj.rand.index(res2$result, truth)

```


##Buettner

```{r Buettner}
i = 4

#read data
load('../data/unnecessary_in_building/4_Buettner.RData')
X        = as.matrix(Buettner$X)
truth    = as.numeric(as.factor(Buettner$label))
numClust = 3
rm(Buettner)

logX = log(X+1)
det = colSums(X!=0) / nrow(X)

det2 = qr(det)
R = t(qr.resid(det2, t(logX)))

pca1 = irlba(R,2); pca2 = irlba(logX,2)
dat = data.frame(pc1=c(pca1$v[,1], pca2$v[,1]), detection.rate=rep(det, 2), label=rep(c("After correction", "Before correction"), each=nrow(pca1$v)), true.label=as.factor(rep(truth,2)))
ggplot(dat, aes(x=pc1, y=detection.rate, col=true.label)) + facet_grid(~label) + geom_point() + ggtitle("PCA")

tsne1 = Rtsne(t(R), perplexity=20)
tsne2 = Rtsne(t(logX), perplexity=20)

dat = data.frame(v1 = c(tsne1$Y[,1], tsne2$Y[,1]), v2 = c(tsne1$Y[,2], tsne2$Y[,2]), label=rep(c("After correction", "Before correction"), each=nrow(tsne1$Y)), true.label = as.factor(rep(truth, 2)))
ggplot(dat, aes(x=v1, y=v2, col=true.label)) + facet_grid(~label) + geom_point() + ggtitle("tSNE")


set.seed(1)
res1 = SLSL(X, log=T, filter=F, correct_detection_rate = T, numClust = numClust)
adj.rand.index(res1$result, truth)

set.seed(1)
res2 = SLSL(X, log=T, filter=F, correct_detection_rate = F, numClust = numClust)
adj.rand.index(res2$result, truth)
```


##Yan 
```{r Yan}
i = 5

load('../data/unnecessary_in_building/5_Yan.rda')
X        = as.matrix(yan)
truth    = as.character(ann$cell_type1)
truth    = as.numeric(as.factor(truth))
numClust = 6
rm(ann, yan)

logX = log(X+1)

det = colSums(X!=0) / nrow(X)

det2 = qr(det)
R = t(qr.resid(det2, t(logX)))

pca1 = irlba(R,2); pca2 = irlba(logX,2)
dat = data.frame(pc1=c(pca1$v[,1], pca2$v[,1]), detection.rate=rep(det, 2), label=rep(c("After correction", "Before correction"), each=nrow(pca1$v)), true.label=as.factor(rep(truth,2)))
ggplot(dat, aes(x=pc1, y=detection.rate, col=true.label)) + facet_grid(~label) + geom_point() + ggtitle("PCA")

tsne1 = Rtsne(t(R), perplexity=20)
tsne2 = Rtsne(t(logX), perplexity=20)

dat = data.frame(v1 = c(tsne1$Y[,1], tsne2$Y[,1]), v2 = c(tsne1$Y[,2], tsne2$Y[,2]), label=rep(c("After correction", "Before correction"), each=nrow(tsne1$Y)), true.label = as.factor(rep(truth, 2)))
ggplot(dat, aes(x=v1, y=v2, col=true.label)) + facet_grid(~label) + geom_point() + ggtitle("tSNE")

set.seed(1)
res1 = SLSL(X, log=T, filter=F, correct_detection_rate = T, numClust = numClust)
adj.rand.index(res1$result, truth)

set.seed(1)
res2 = SLSL(X, log=T, filter=F, correct_detection_rate = F, numClust = numClust)
adj.rand.index(res2$result, truth)

```


## Treutlein

```{r Treutlein}
i = 6

load('../data/unnecessary_in_building/6_Treutlein.rda')
X        = as.matrix(treutlein)
truth    = as.numeric(colnames(treutlein))
ind      = sort(truth, index.return=TRUE)$ix
X        = X[,ind]
truth    = truth[ind]
numClust = length(unique(truth))
rm(treutlein)
logX = log(X+1)

det = colSums(X!=0) / nrow(X)

det2 = qr(cbind(log(det), rep(1, length(det))))
R = t(qr.resid(det2, t(logX)))

pca1 = irlba(R,2); pca2 = irlba(logX,2)
dat = data.frame(pc1=c(pca1$v[,1], pca2$v[,1]), detection.rate=rep(det, 2), label=rep(c("After correction", "Before correction"), each=nrow(pca1$v)), true.label=as.factor(rep(truth,2)))
ggplot(dat, aes(x=pc1, y=detection.rate, col=true.label)) + facet_grid(~label) + geom_point() + ggtitle("PCA")

tsne1 = Rtsne(t(R), perplexity=10)
tsne2 = Rtsne(t(logX), perplexity=10)

dat = data.frame(v1 = c(tsne1$Y[,1], tsne2$Y[,1]), v2 = c(tsne1$Y[,2], tsne2$Y[,2]), label=rep(c("After correction", "Before correction"), each=nrow(tsne1$Y)), true.label = as.factor(rep(truth, 2)))
ggplot(dat, aes(x=v1, y=v2, col=true.label)) + facet_grid(~label) + geom_point() + ggtitle("tSNE")

set.seed(1)
res1 = SLSL(X, log=T, filter=F, correct_detection_rate = T, numClust = numClust)
adj.rand.index(res1$result, truth)

set.seed(1)
res2 = SLSL(X, log=T, filter=F, correct_detection_rate = F, numClust = numClust)
adj.rand.index(res2$result, truth)
```

## Chu (cell type)

```{r Chu_celltype, cache=T}
i = 7

load('../data/unnecessary_in_building/7_Chu_celltype.Rdata')
X        = as.matrix(Chu_celltype$X)
truth    = as.numeric(as.factor(Chu_celltype$label))
numClust = 7
rm(Chu_celltype)

logX = log(X+1)

det = colSums(X!=0) / nrow(X)

det2 = qr(det)
R = t(qr.resid(det2, t(logX)))

pca1 = irlba(R,2); pca2 = irlba(logX,2)
dat = data.frame(pc1=c(pca1$v[,1], pca2$v[,1]), detection.rate=rep(det, 2), label=rep(c("After correction", "Before correction"), each=nrow(pca1$v)), true.label=as.factor(rep(truth,2)))
ggplot(dat, aes(x=pc1, y=detection.rate, col=true.label)) + facet_grid(~label) + geom_point() + ggtitle("PCA")

tsne1 = Rtsne(t(R))
tsne2 = Rtsne(t(logX))

dat = data.frame(v1 = c(tsne1$Y[,1], tsne2$Y[,1]), v2 = c(tsne1$Y[,2], tsne2$Y[,2]), label=rep(c("After correction", "Before correction"), each=nrow(tsne1$Y)), true.label = as.factor(rep(truth, 2)))
ggplot(dat, aes(x=v1, y=v2, col=true.label)) + facet_grid(~label) + geom_point() + ggtitle("tSNE")

set.seed(1)
res1 = SLSL(X, log=T, filter=F, correct_detection_rate = T, numClust = numClust)
adj.rand.index(res1$result, truth)

set.seed(1)
res2 = SLSL(X, log=T, filter=F, correct_detection_rate = F, numClust = numClust)
adj.rand.index(res2$result, truth)
```

## Chu (timecourse)

```{r Chu_timecourse, cache=T}
i = 8
load('../data/unnecessary_in_building/8_Chu_timecourse.Rdata')
X        = as.matrix(Chu_timecourse$X)
truth    = as.numeric(as.factor(Chu_timecourse$label))
numClust = length(unique(truth))

logX = log(X+1)

det = colSums(X!=0) / nrow(X)

det2 = qr(det)
R = t(qr.resid(det2, t(logX)))

pca1 = irlba(R,2); pca2 = irlba(logX,2)
dat = data.frame(pc1=c(pca1$v[,1], pca2$v[,1]), detection.rate=rep(det, 2), label=rep(c("After correction", "Before correction"), each=nrow(pca1$v)), true.label=as.factor(rep(truth,2)))
ggplot(dat, aes(x=pc1, y=detection.rate, col=true.label)) + facet_grid(~label) + geom_point() + ggtitle("PCA")

tsne1 = Rtsne(t(R))
tsne2 = Rtsne(t(logX))

dat = data.frame(v1 = c(tsne1$Y[,1], tsne2$Y[,1]), v2 = c(tsne1$Y[,2], tsne2$Y[,2]), label=rep(c("After correction", "Before correction"), each=nrow(tsne1$Y)), true.label = as.factor(rep(truth, 2)))
ggplot(dat, aes(x=v1, y=v2, col=true.label)) + facet_grid(~label) + geom_point() + ggtitle("tSNE")

set.seed(1)
res1 = SLSL(X, log=T, filter=F, correct_detection_rate = T, numClust = numClust)
adj.rand.index(res1$result, truth)

set.seed(1)
res2 = SLSL(X, log=T, filter=F, correct_detection_rate = F, numClust = numClust)
adj.rand.index(res2$result, truth)
```

