# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

proj_c <- function(X, ref) {
    .Call('_SCNoisyClustering_proj_c', PACKAGE = 'SCNoisyClustering', X, ref)
}

armapmax <- function(A, bound) {
    .Call('_SCNoisyClustering_armapmax', PACKAGE = 'SCNoisyClustering', A, bound)
}

armapmin <- function(A, bound) {
    .Call('_SCNoisyClustering_armapmin', PACKAGE = 'SCNoisyClustering', A, bound)
}

nonnegASC_c <- function(B) {
    .Call('_SCNoisyClustering_nonnegASC_c', PACKAGE = 'SCNoisyClustering', B)
}

dist_c <- function(X) {
    .Call('_SCNoisyClustering_dist_c', PACKAGE = 'SCNoisyClustering', X)
}

get_rank <- function(X) {
    .Call('_SCNoisyClustering_get_rank', PACKAGE = 'SCNoisyClustering', X)
}

spearman_c <- function(X) {
    .Call('_SCNoisyClustering_spearman_c', PACKAGE = 'SCNoisyClustering', X)
}

corr_kernel_c <- function(X, Diff, allk_input, sigma_input, k = 0L) {
    .Call('_SCNoisyClustering_corr_kernel_c', PACKAGE = 'SCNoisyClustering', X, Diff, allk_input, sigma_input, k)
}

dist_kernel_c <- function(X, allk_input, sigma_input, k = 0L) {
    .Call('_SCNoisyClustering_dist_kernel_c', PACKAGE = 'SCNoisyClustering', X, allk_input, sigma_input, k)
}

rank_kernel_c <- function(X, Diff, allk_input, sigma_input, k = 0L) {
    .Call('_SCNoisyClustering_rank_kernel_c', PACKAGE = 'SCNoisyClustering', X, Diff, allk_input, sigma_input, k)
}

sparse_scaledlasso_c <- function(P, tau, gamma, mu = 1e-3, rho = 1.9, max_iter = 100L, eps = 1e-7, verbose = FALSE) {
    .Call('_SCNoisyClustering_sparse_scaledlasso_c', PACKAGE = 'SCNoisyClustering', P, tau, gamma, mu, rho, max_iter, eps, verbose)
}

tsne_c <- function(X, initial_config, k, max_iter = 1000L, min_cost = 1e-3, epoch = 100L) {
    .Call('_SCNoisyClustering_tsne_c', PACKAGE = 'SCNoisyClustering', X, initial_config, k, max_iter, min_cost, epoch)
}

