# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sparse_sum <- function(P, length) {
    .Call('_SCNoisyClustering_sparse_sum', PACKAGE = 'SCNoisyClustering', P, length)
}

QminusPslice <- function(Q, P, length) {
    .Call('_SCNoisyClustering_QminusPslice', PACKAGE = 'SCNoisyClustering', Q, P, length)
}

proj_c <- function(X, ref) {
    .Call('_SCNoisyClustering_proj_c', PACKAGE = 'SCNoisyClustering', X, ref)
}

armapmax <- function(A, bound) {
    .Call('_SCNoisyClustering_armapmax', PACKAGE = 'SCNoisyClustering', A, bound)
}

armapmin <- function(A, bound) {
    .Call('_SCNoisyClustering_armapmin', PACKAGE = 'SCNoisyClustering', A, bound)
}

nonnegASC_c <- function(B) {
    .Call('_SCNoisyClustering_nonnegASC_c', PACKAGE = 'SCNoisyClustering', B)
}

get_kernel_matrix <- function(X, Diff, k, sigma) {
    .Call('_SCNoisyClustering_get_kernel_matrix', PACKAGE = 'SCNoisyClustering', X, Diff, k, sigma)
}

sparse_scaledlasso_list_c <- function(P, n, tau, gamma, mu = 1e-3, rho = 1.9, max_iter = 100L, eps = 1e-9, verbose = FALSE) {
    .Call('_SCNoisyClustering_sparse_scaledlasso_list_c', PACKAGE = 'SCNoisyClustering', P, n, tau, gamma, mu, rho, max_iter, eps, verbose)
}

tsne_c <- function(X, initial_config, k, max_iter = 1000L, min_cost = 1e-3, epoch = 100L) {
    .Call('_SCNoisyClustering_tsne_c', PACKAGE = 'SCNoisyClustering', X, initial_config, k, max_iter, min_cost, epoch)
}

