# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ic_c <- function(k, Y, phi, xi, theta, p, n) {
    .Call('_SCNoisyClustering_ic_c', PACKAGE = 'SCNoisyClustering', k, Y, phi, xi, theta, p, n)
}

